#!/bin/bash

echo "🚀 Building Flutter Web App..."
cd /workspaces/TokerrGjiks/tokerrgjik_mobile
flutter build web --release --web-renderer canvaskit --no-tree-shake-icons

echo ""
echo "✅ Build Complete!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📦 DEPLOYMENT OPTIONS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "OPTION 1: NETLIFY DROP (EASIEST - NO CLI NEEDED)"
echo "  1. Open: https://app.netlify.com/drop"
echo "  2. Drag folder: /workspaces/TokerrGjiks/tokerrgjik_mobile/build/web"
echo "  3. Get instant URL!"
echo ""
echo "OPTION 2: FIREBASE HOSTING (FREE, FAST)"
echo "  Run: npm install -g firebase-tools"
echo "  Run: firebase login"
echo "  Run: firebase init hosting"
echo "  Run: firebase deploy"
echo ""
echo "OPTION 3: GITHUB PAGES (FREE)"
echo "  Just push to 'gh-pages' branch:"
echo "  cd /workspaces/TokerrGjiks"
echo "  git checkout -b gh-pages"
echo "  cp -r tokerrgjik_mobile/build/web/* ."
echo "  git add ."
echo "  git commit -m 'Deploy to GitHub Pages'"
echo "  git push origin gh-pages"
echo "  Enable in: Settings > Pages > Source: gh-pages"
echo ""
echo "Build location: /workspaces/TokerrGjiks/tokerrgjik_mobile/build/web"
echo "═══════════════════════════════════════════════════════════════"
