[build]
  # No build command - we'll push pre-built files
  # Build locally with: cd tokerrgjik_mobile && flutter build web --release
  command = "echo 'Using pre-built Flutter web files'"
  publish = "tokerrgjik_mobile/build/web"
  functions = "netlify/functions"

[build.environment]
  # Not needed since we're using pre-built files
  NODE_VERSION = "18"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "echo 'Using pre-built Flutter web files for production'"

[context.deploy-preview]
  command = "echo 'Using pre-built Flutter web files for preview'"

[context.branch-deploy]
  command = "echo 'Using pre-built Flutter web files for branch'"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
