[build]
  base = "tokerrgjik_mobile"
  command = "flutter build web --release --web-renderer canvaskit"
  publish = "tokerrgjik_mobile/build/web"
  functions = "netlify/functions"

[build.environment]
  # Flutter version
  FLUTTER_VERSION = "3.35.6"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[context.production]
  command = "flutter build web --release --web-renderer canvaskit"

[context.deploy-preview]
  command = "flutter build web --release --web-renderer canvaskit"

[context.branch-deploy]
  command = "flutter build web --release --web-renderer canvaskit"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
