apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokerrgjik-backend
  labels:
    app: tokerrgjik
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokerrgjik
      component: backend
  template:
    metadata:
      labels:
        app: tokerrgjik
        component: backend
    spec:
      containers:
      - name: backend
        image: ejupishaban/tokerrgjik-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tokerrgjik-backend-service
spec:
  selector:
    app: tokerrgjik
    component: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
