name: Build Android & iOS Apps

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-android:
    name: Build Android APK/AAB
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
        
      - name: Generate API keys
        working-directory: tokerrgjik_mobile
        run: |
          # Copy template file to actual config
          if [ -f lib/config/api_keys.dart.template ]; then
            cp lib/config/api_keys.dart.template lib/config/api_keys.dart
            echo "✅ API keys generated from template"
          else
            echo "⚠️  No template found, creating empty config"
            cat > lib/config/api_keys.dart <<EOF
          class ApiKeys {
            static const String admobAppIdAndroid = '';
            static const String admobAppIdIos = '';
            static const String admobBannerAndroid = '';
            static const String admobBannerIos = '';
            static const String admobInterstitialAndroid = '';
            static const String admobInterstitialIos = '';
            static const String admobRewardedAndroid = '';
            static const String admobRewardedIos = '';
          }
          EOF
          fi
      
      - name: Get dependencies
        working-directory: tokerrgjik_mobile
        run: flutter pub get
      
      - name: Fix Android Gradle compileSdk
        working-directory: tokerrgjik_mobile/android
        run: |
          # Add compileSdkVersion fix for package_info_plus plugin
          # This ensures all subprojects compile with SDK 36
          if ! grep -q "compileSdkVersion(36)" build.gradle.kts; then
            sed -i '/afterEvaluate {/a\        compileSdkVersion(36)' build.gradle.kts
            echo "✅ Added compileSdkVersion(36) to build.gradle.kts"
          else
            echo "✅ compileSdkVersion already configured"
          fi
      
      - name: Build APK (Release)
        working-directory: tokerrgjik_mobile
        run: flutter build apk --release --split-per-abi
      
      - name: Build App Bundle (Release)
        working-directory: tokerrgjik_mobile
        run: flutter build appbundle --release
      
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            tokerrgjik_mobile/build/app/outputs/flutter-apk/*.apk
          retention-days: 90
      
      - name: Upload AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: |
            tokerrgjik_mobile/build/app/outputs/bundle/release/*.aab
          retention-days: 90
      
      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tokerrgjik_mobile/build/app/outputs/flutter-apk/*.apk
            tokerrgjik_mobile/build/app/outputs/bundle/release/*.aab
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ios:
    name: Build iOS IPA
    runs-on: macos-14  # macOS with Apple Silicon
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
      
      - name: Generate API keys
        working-directory: tokerrgjik_mobile
        run: |
          # Copy template file to actual config
          if [ -f lib/config/api_keys.dart.template ]; then
            cp lib/config/api_keys.dart.template lib/config/api_keys.dart
            echo "✅ API keys generated from template"
          else
            echo "⚠️  No template found, creating empty config"
            cat > lib/config/api_keys.dart <<EOF
          class ApiKeys {
            static const String admobAppIdAndroid = '';
            static const String admobAppIdIos = '';
            static const String admobBannerAndroid = '';
            static const String admobBannerIos = '';
            static const String admobInterstitialAndroid = '';
            static const String admobInterstitialIos = '';
            static const String admobRewardedAndroid = '';
            static const String admobRewardedIos = '';
          }
          EOF
          fi
      
      - name: Get dependencies
        working-directory: tokerrgjik_mobile
        run: flutter pub get
      
      - name: Build iOS (No Codesign)
        working-directory: tokerrgjik_mobile
        run: flutter build ios --release --no-codesign
      
      - name: Create IPA
        working-directory: tokerrgjik_mobile
        run: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/Tokerrgjik.ipa Payload/
          rm -rf Payload
      
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: tokerrgjik_mobile/build/ios/ipa/*.ipa
          retention-days: 90
      
      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: tokerrgjik_mobile/build/ios/ipa/*.ipa
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-web:
    name: Build Web Version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
      
      - name: Generate API keys
        working-directory: tokerrgjik_mobile
        run: |
          # Copy template file to actual config
          if [ -f lib/config/api_keys.dart.template ]; then
            cp lib/config/api_keys.dart.template lib/config/api_keys.dart
            echo "✅ API keys generated from template"
          else
            echo "⚠️  No template found, creating empty config"
            cat > lib/config/api_keys.dart <<EOF
          class ApiKeys {
            static const String admobAppIdAndroid = '';
            static const String admobAppIdIos = '';
            static const String admobBannerAndroid = '';
            static const String admobBannerIos = '';
            static const String admobInterstitialAndroid = '';
            static const String admobInterstitialIos = '';
            static const String admobRewardedAndroid = '';
            static const String admobRewardedIos = '';
          }
          EOF
          fi
      
      - name: Get dependencies
        working-directory: tokerrgjik_mobile
        run: flutter pub get
      
      - name: Build Web
        working-directory: tokerrgjik_mobile
        run: flutter build web --release
      
      - name: Upload Web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: tokerrgjik_mobile/build/web/
          retention-days: 90
